### ISSUE TITLE
IOException [CRITICAL]

### ISSUE THREAD

**Issue by iarsslen** [Snowl/Poro#2]
This Exception was the reason of failling every RTMP Request. Any help pls

System.IO.IOException was caught
  HResult=-2146232800
  Message=Unable to read data from the transport connection: An established connection was aborted by the software in your host machine.
  Source=System
  StackTrace:
       at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
       at System.Net.FixedSizeReader.StartReading()
       at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
       at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
       at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
       at System.Net.Security._SslStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
       at System.Net.Security.SslStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
       at System.IO.Stream.<BeginEndReadAsync>b__d(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
       at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
       à System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
       à System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
       à System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
       à RtmpSharp.IO.StreamHelper.<ReadBytesAsync>d__0.MoveNext() dans d:\Projects\LeagueHelper\Poro\rtmp-sharp\IO\StreamHelper.cs:ligne 46

--- End stack trace from the previous location at which the exception was thrown ---

```
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à RtmpSharp.Net.RtmpHandshake.<ReadAsync>d__2.MoveNext() dans d:\Projects\LeagueHelper\Poro\rtmp-sharp\Net\RtmpHandshake.cs:ligne 39
```

 --- End stack trace from the previous location at which the exception was thrown ---

```
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à RtmpSharp.Net.RtmpServer.<OnClientAccepted>d__3.MoveNext() dans d:\Projects\LeagueHelper\Poro\rtmp-sharp\Net\RtmpServer.cs:ligne 88
```

  InnerException: System.Net.Sockets.SocketException
       HResult=-2147467259
       Message=An established connection was aborted by the software in your host machine
       Source=System
       ErrorCode=10053
       NativeErrorCode=10053
       StackTrace:
            à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
            à System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
       InnerException:

**Comment by Arsslensoft** [comment]
Problem Solved by matching the IP address in the CERTIFICATE AND LOCAL IP of the SERVER.

**Comment by iarsslen** [comment]
Problem Solved by matching the IP address in the CERTIFICATE AND LOCAL IP of the SERVER.
